#!/bin/bash
echo "Apt-get upgrade"
mv /etc/kernel/postinst.d/zz-update-grub /chroot/zz-update-grub 
apt-get dist-upgrade -y
apt-get autoremove -y
apt-get install -fy
mv /chroot/zz-update-grub /etc/kernel/postinst.d/zz-update-grub