#!/bin/bash
echo "+++ CONFIGURING LIVE ISO"
./chroot/apt-cacher-update
./chroot/apt-get-dist-upgrade
./chroot/install-ubuntu-restricted-extras
./chroot/enable-network-manager
./chroot/install-oem-config
./chroot/post-apt-get-dist-upgrade-cleanup
./chroot/apt-cacher-remove