#!/bin/bash
./chroot/apt-cacher-apt-get-update
./chroot/apt-get-dist-upgrade
./chroot/install-ubuntu-restricted-extras
./chroot/enable-network-manager
./chroot/install-oem-config
./chroot/post-dist-upgrade-cleanup