#!/bin/bash
# Kirtley Wienbroer
# kirtley@osgenie.com
echo "Apt-get Update"
export http_proxy=http://192.168.11.10:3142
rm -f /target/etc/apt/sources.list.d/dvd.list
apt-get update -qq
echo "Apt-get upgrade"
mv /etc/kernel/postinst.d/zz-update-grub /chroot/zz-update-grub 
apt-get dist-upgrade -y
apt-get autoremove -y
apt-get install -fy
mv /chroot/zz-update-grub /etc/kernel/postinst.d/zz-update-grub 
echo "Running Configurations"
./chroot/install-ubuntu-restricted-extras
./chroot/enable-network-manager
echo "Clean up desktop icons"
apt-get purge -y ubiquity
rm -v /etc/skel/examples.desktop
echo "Apt-get clean"
apt-get clean -y
echo "All done!"