#!/bin/bash
# Kirtley Wienbroer
# kirtley@osgenie.com
echo "Apt-get Update"
export http_proxy=http://192.168.11.6:3142
apt-get update
echo "Apt-get upgrade"
apt-get upgrade -y
apt-get autoremove -y
apt-get install -fy
echo "Running Configurations"
./chroot/install-oem-config
./chroot/install-ubuntu-restricted-extras
./chroot/enable-network-manager
echo "Apt-get clean"
apt-get clean -y
echo "All done!"