#!/bin/bash
# Kirtley Wienbroer
# kirtley@osgenie.com
# Written with the help of http://unixblogger.wordpress.com/2011/10/18/the-pain-of-an-realtek-rtl8111rtl8168-ethernet-card/
# July 13 2012

# Install prerequisites
apt-get install -y build-essential
apt-get install -y linux-headers-`uname -r`

# Blacklist the origional driver
echo "blacklist r8169" >> /etc/modprobe.d/blacklist.conf

# RTL8169 PCI ethernet
cd /tmp
wget ftp://WebUser:r3iZ6vJI@207.232.93.28/cn/nic/r8169-6.017.00.tar.bz2
tar xjf r8169-6.017.00.tar.bz2
cd r8169-6.017.00
# build the driver
make clean modules
make install
# install the driver
depmod -a
#insmod ./src/r8169.ko
# Make it available for boot
# mkinitramfs -o /boot/initrd.img-`uname -r` `uname -r`
echo "r8169" >> /etc/modules

# Cleanup
rm -rf /tmp/*