#!/bin/bash
echo "Apt-get upgrade"
mv /etc/kernel/postinst.d/zz-update-grub /chroot/zz-update-grub 
apt-get upgrade -qq
apt-get install -fy
mv /chroot/zz-update-grub /etc/kernel/postinst.d/zz-update-grub
echo "Apt-get clean"
apt-get clean -qq
apt-get autoremove -qq
echo "All done!"